SELECT EXTRACT (DAY FROM CURRENT_DATE);

SELECT CURRENT_TIMESTAMP, EXTRACT(HOUR FROM CURRENT_TIMESTAMP);

SELECT order_date, ship_date, (EXTRACT(EPOCH FROM ship_date) - EXTRACT(EPOCH FROM order_date)) AS time_taken
FROM sales;
